version: '3.6'
services:
  shadowsocks:  
    build: .
  #  image: shadowsocks/shadowsocks-libev
    ports:
      - "8488:8388/tcp"
      - "8488:8388/udp"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=9MLSpPmNt
    restart: always
